@startuml

participant Customer
participant Controller
participant Service
database DB

group #LightBlue "Check Availability"

Customer -> Controller: asd
rnote over Customer

end note

Controller -> Service
rnote over Controller

end note

Service -> DB
rnote over Service

end note

DB --> Service
rnote over DB

end note

Service --> Controller
rnote over Service

end note

Controller --> Customer
rnote over Controller

end note


end


@enduml